GamePortal/GP.Web/Controllers/ApiTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GP.Web.Controllers
{
    public class ApiTestController : Controller
    {
        //
        // GET: /ApiTest/

        public ActionResult Index()
        {
            return View();
        }

    }
}

GamePortal/GP.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GP.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GamePortal/GP.Web/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using GP.Web.DAL;

namespace GP.Web.Controllers
{
    public class UserInfoController : ApiController
    {
        private gamedb db = new gamedb();

        // GET api/UserInfo
        public IEnumerable<userinfo> Getuserinfoes()
        {
            return db.userinfo.AsEnumerable();
        }

        // GET api/UserInfo/5
        public userinfo Getuserinfo(long id)
        {
            userinfo userinfo = db.userinfo.Find(id);
            if (userinfo == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return userinfo;
        }

        // PUT api/UserInfo/5
        public HttpResponseMessage Putuserinfo(long id, userinfo userinfo)
        {
            if (!ModelState.IsValid)
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }

            if (id != userinfo.id)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }

            db.Entry(userinfo).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                return Request.CreateErrorResponse(HttpStatusCode.NotFound, ex);
            }

            return Request.CreateResponse(HttpStatusCode.OK);
        }

        // POST api/UserInfo
        public HttpResponseMessage Postuserinfo(userinfo userinfo)
        {
            if (ModelState.IsValid)
            {
                db.userinfo.Add(userinfo);
                db.SaveChanges();

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.Created, userinfo);
                response.Headers.Location = new Uri(Url.Link("DefaultApi", new { id = userinfo.id }));
                return response;
            }
            else
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }
        }

        // DELETE api/UserInfo/5
        public HttpResponseMessage Deleteuserinfo(long id)
        {
            userinfo userinfo = db.userinfo.Find(id);
            if (userinfo == null)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            db.userinfo.Remove(userinfo);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                return Request.CreateErrorResponse(HttpStatusCode.NotFound, ex);
            }

            return Request.CreateResponse(HttpStatusCode.OK, userinfo);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GamePortal/GP.Web/Views/ApiTest/Index.cshtml
@using System.Web.Http
@using GP.Web
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div class="container">
    <div>
        method:
        <select>
            <option value="GET">GET</option>
            <option value="POST">POST</option>
            <option value="PUT">PUT</option>
            <option value="DELETE">DELETE</option>
        </select>
        url:
        <input type="text"/>
    </div>

</div>
<div id="testClientDialog" title="description.HttpMethod description.RelativePath">
    <input class="httpMethod" spellcheck="false" data-bind="value: HttpMethod" />
    <input class="uriPath" spellcheck="false" data-bind="value: UriPath" />
    <div data-bind="visible: UriParameters.length > 0">
        <h5 class="ui-widget-header">URI parameters</h5>
        <div class="panel">
            <div data-bind="foreach: UriParameters">
                <div>
                    <input readonly="readonly" spellcheck="false" tabindex="100" class="uriParameterLabel" data-bind="value: '{' + name + '}'" />
                    <span>= </span>
                    <input spellcheck="false" data-bind="value: value, valueUpdate: 'afterkeydown', enable: enabled" />
                    <input type="checkbox" data-bind="checked: enabled" />
                </div>
            </div>
        </div>
    </div>
    <h5 class="ui-widget-header">
        Headers | <a style="text-decoration: underline" href="#" data-bind="click: addHeader">Add header</a>
    </h5>
    <div class="panel">
        <div data-bind="foreach: RequestHeaders">
            <div>
                <input spellcheck="false" data-bind='value: name, uniqueName: true' />
                <span>: </span>
                <input spellcheck="false" data-bind='value: value, uniqueName: true' />
                <a href='#' data-bind='click: $root.removeHeader'>Delete</a>
            </div>
        </div>
    </div>
    <h5 class="ui-widget-header">
        <input type='checkbox' data-bind='checked: ShouldShowBody' />Body
    </h5>
    <div data-bind="visible: ShouldShowBody">
        <div data-bind="visible: SampleTypes.length > 0">
            <span>Samples: </span>
            <select data-bind="options: SampleTypes, value: RequestMediaType"></select>
        </div>
        <pre><textarea class="sampleArea" spellcheck="false" data-bind="value: RequestBody, valueUpdate: 'afterkeydown'" rows="7"></textarea></pre>
    </div>
</div>

<div id="testClientResponseDialog" title="Response for description.HttpMethod description.RelativePath" data-bind="with: response">
    <div class="responseStatusDiv">
        <h5 class="ui-widget-header">Status</h5>
        <span data-bind="text: status"></span>
    </div>
    <div class="responseHeaderDiv">
        <h5 class="ui-widget-header">Headers</h5>
        <textarea spellcheck="false" data-bind="value: headers" class="sampleArea" readonly='readonly' rows="6"></textarea>
    </div>
    <div class="responseBodyDiv">
        <h5 class="ui-widget-header">Body</h5>
        <textarea spellcheck="false" data-bind="value: content" class="sampleArea" readonly='readonly' rows="10"></textarea>
    </div>
</div>

GamePortal/GP.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

GamePortal/GP.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

GamePortal/GP.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>

GamePortal/GP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/bootstrap")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/angularjs")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Api test", "Index", "ApiTest")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>